
spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoint:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoints:
    health:
      probes:
        enabled: true
