build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Taha GUL - Developer"
    email: "eskidostlar0625@gmail.com"
  onCallSupport:
    - (555) 555-5555
    - (666) 666-6666